services:
  - type: web
    name: policia-local-vigo
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: PYTHONUNBUFFERED
        value: true
    plan: starter